### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by flip111** [davefx/PHPlot#1]
Can you please make a release so that it will be a stable version? thanks

**Comment by paazmaya** [comment]
Perhaps tag v6.1.0 as it seems to be the one referred as current master.

**Comment by paazmaya** [comment]
Ping

**Comment by chriseskow** [comment]
:+1:

**Comment by thebatclaudio** [comment]
Make a stable release please!

**Comment by davefx** [comment]
Ok. Done. Sorry for the delay!
